---
title: "Your A4 Report Title (TODO: Revise title)"
author: "Ian Paul"
date: '2022-11-01'
output: html_document
---

```{r echo=FALSE, eval=TRUE, message=FALSE}
source("../source/a4-helpers.R")
source("../source/analysis.R")
```

## Abstract 

Racism is one of the longest standing problems that humanity has faced since the beginning of civilization. In America, it is no different. Although
at one point our justice system was one of the first to claim "innocent until proven guilty" it is essential to prove of its upholding. Through the 
analysis of prison system data, we can determine whether race can affect how people are treated in the justice system. 

## Introduction 

This specific data set is one that is meant to expose inequalities in the incarceration systems in America. These issues are deep rooted in the progressive fight for American Equality and this evidence could either prove or disprove the effectiveness of that fight. The direct stakeholders of these data sets would be data scientists, researchers, journalists, and people affected by unequal incarceration. The indirect stakeholders would be prison systems and people affected by this incarceration. In interpreting this data, I have to engage unbiased values that do not look at the data with any specific narrative. In order to find the truth, it is essential to approach in an unbiased manner. Not only this, but it is important to keep the indirect stakeholder of this data in mind and be conscious of the effect that your interpretation will bring on them. In this report, I will be answering the questions: Are there data patterns that show patterns of inequality? Where is this incarceration most prominent?


## Data Summary 



